### ISSUE TITLE
Clarity on one or multiple data plane solutions

### ISSUE THREAD

**Issue by JoelHalpern** [ietf-wg-spring/draft-ietf-spring-srv6-srh-compression#1]
Given that the working group has said that it wants to standardize one
data plane solution, and given that the document contains multiple SRv6
EndPoint behaviors that some WG members have stated are multiple data
plane solutions, the working group will address whether this is valid
and coherent with its one data plane solution objective.

**Comment by fclad-ietf** [comment]
All SIDs of the SRv6 dataplane (defined in this document and in other documents) can co-exist in the same SRH. This make SRv6 a single, consistent dataplane solution.

**Comment by JoelHalpern** [comment]
THE WG has concluded that this document is consistent with the agreed approach.
