### ISSUE TITLE
Conformance to existing RFCs

### ISSUE THREAD

**Issue by JoelHalpern** [ietf-wg-spring/draft-ietf-spring-srv6-srh-compression#2]
As reminded in the conclusion of the adoption call, this document is 
subject to the policy announced by the SPRING chairs in 
https://mailarchive.ietf.org/arch/msg/spring/vCc9Ckvwu5HA-RCleV712dsA5OA/.
In particular, this means that this document can not go to WG last call 
until 6man completes handling of an Internet Draft that deals with the 
relationship of C-SIDs to RFC 4291.  It is hoped and expected that said 
resolution will be a WG last call and document approval in 6man of a 
document providing for the way that C-SIDs use the IPv6 destination 
address field.
The document currently being looked at for this is https://datatracker.ietf.org/doc/html/draft-krishnan-6man-sids

**Comment by fclad-ietf** [comment]
draft-ietf-6man-sids addresses this issue and it has been WG Last Called by 6man.

**Comment by JoelHalpern** [comment]
Closed as per WG Poll.
