### ISSUE TITLE
Updated definition for SegmentsLeft Field needed

### ISSUE THREAD

**Issue by sureshkrishnan** [ietf-wg-spring/draft-ietf-spring-srv6-srh-compression#3]
The definition for the SegmentsLeft field of the SRH as currently stated in [RFC8754][RFC8200] no longer holds true in the presence of C-SIDs. This definition needs to be updated to still hold true in the presence of C-SIDs.

**Comment by fclad-ietf** [comment]
[Verified errata 7102](https://www.rfc-editor.org/errata/eid7102) for RFC 8754 updates the Segments Left definition as follows:

> Segments Left: Defined in [RFC8200], Section 4.4. Specifically, for the SRH, the number of unprocessed 128-bit entries in the Segment List.

**Comment by JoelHalpern** [comment]
Closed as per WG poll.
